import {Dimensions, StyleSheet} from 'react-native';

const Styles = StyleSheet.create({
  Dashboardhome: {
    width: '100%',
    minHeight: Dimensions.get('window').height,
    backgroundColor: '#222433',
  },
  Dashboardheader: {
    minHeight: 80,
    color: 'white',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 20,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
  },
  dashboardgreeting: {
    color: 'rgba(255, 255,255, 0.6)',
    fontSize: 29,
    // fontWeight: '900',
  },
  dashboardUser: {
    color: 'rgba(255, 255,255, 0.8)',
    fontSize: 26,
    // marginHorizontal: 7,
    fontWeight: '700',

    textTransform: 'capitalize',
  },
  Userlink: {
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    marginVertical: 20,
    // color:"black",
    height: 60,
    borderRadius: 15,
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderColor: 'rgba(0,0,0,0.4)',
    borderWidth: 1,
  },
  Socialshare: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderRadius: 30,
  },
  messagetitle: {
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  messagetitletext: {
    fontSize: 22,
    color: 'white',
    fontWeight: '600',
  },
  Messagecontainer: {
    paddingHorizontal: 20,
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  messagesbackground: {
    width: '100%',
    height: '100%',
    backgroundColor: 'yellow',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    // margin: 5,
  },
  linearGradient: {
    flex: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
  },
  Templates: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    paddingVertical: 15,
  },
  Templatescontainer: {
    width: '95%',
    backgroundColor: 'white',
    height: 170,
    borderRadius: 15,
    display: 'flex',
    alignItems: 'center',
    paddingVertical: 10,
    marginVertical: 10,
  },
  Intructions: {
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
    position: 'absolute',
    // top: 30,
    zIndex: 10000,
    // left: 10,
    backgroundColor: 'rgba(0,0,0,0.3)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  instructionscontainer: {
    width: '90%',
    maxHeight: '55%',
    backgroundColor: 'white',
    borderRadius: 10,
  },
});

export {Styles};
